# Generated by Django 5.0.7 on 2024-08-17 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teach', '0008_remove_kit_is_passed'),
        ('users', '0006_student_passed_kits'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kits', models.ManyToManyField(help_text='Выберите или добавьте набор', to='teach.kit', verbose_name='наборы')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student', verbose_name='ученик')),
            ],
        ),
    ]
