# Generated by Django 5.0.7 on 2024-08-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(help_text='Выберите или добавьте ученика', to='users.student', verbose_name='ученики'),
        ),
    ]
