# Generated by Django 5.0.7 on 2024-08-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0008_remove_kit_is_passed'),
        ('users', '0006_student_passed_kits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passed_kits',
            field=models.ManyToManyField(blank=True, null=True, to='teach.kit', verbose_name='пройденные наборы'),
        ),
    ]
