# Generated by Django 5.0.7 on 2024-07-28 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=150, unique=True, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='название')),
                ('card', models.ForeignKey(blank=True, default=None, help_text='Добавьте в набор карточки', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards_kit', related_query_name='cards_kit', to='teach.card', verbose_name='Карточки')),
            ],
            options={
                'verbose_name': 'набор',
                'verbose_name_plural': 'наборы',
            },
        ),
    ]
