# Generated by Django 5.0.7 on 2024-07-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0002_kit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='card',
        ),
        migrations.AddField(
            model_name='kit',
            name='cards',
            field=models.ManyToManyField(help_text='Выберите или добавьте карточку', to='teach.card', verbose_name='карточки'),
        ),
    ]
