# Generated by Django 5.0.7 on 2024-07-28 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0004_card_user_kit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='word',
            field=models.CharField(help_text='Введите слово', max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='слово'),
        ),
    ]
