# Generated by Django 5.0.7 on 2024-08-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0006_alter_card_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='пройденый'),
        ),
    ]
